spring.application.name=rag-demo

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/vector_db
spring.datasource.username=yann
spring.datasource.password=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring AI Vector Store Configuration
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.initialize-schema=true

# Ollama Configuration (Local Embeddings & Chat)
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text-v2-moe:latest
spring.ai.ollama.chat.options.model=glm-4.6:cloud


server.port=8080

# File Upload Limit
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Thymeleaf - disable cache for development
spring.thymeleaf.cache=false


