spring.application.name=ui-gateway-service
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false

# File Upload Limit
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# URLs des services Backend
app.services.ingestion.url=http://localhost:8081
app.services.retriever.url=http://localhost:8082

# Models UI
app.available-models=glm-4.6:cloud,qwen3:4b,llama3.2:3b,gemma4:e2b
